# Generated by Django 4.2.13 on 2024-06-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0047_alter_conductor_options_alter_creatives_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backstage',
            options={'ordering': ['date'], 'verbose_name_plural': 'Backstage'},
        ),
        migrations.RenameField(
            model_name='backstage',
            old_name='type',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block1_content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block1_media',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block1_picture',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block1_type',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block2_content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block2_media',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block2_picture',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block2_type',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block3_content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block3_media',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block3_picture',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block3_type',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block4_content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block4_media',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block4_picture',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block4_type',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block5_content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block5_media',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block5_picture',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='block5_type',
        ),
        migrations.CreateModel(
            name='BackstageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('text_content', models.TextField(blank=True, max_length=10000, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='backstage/')),
                ('video_content', models.FileField(blank=True, null=True, upload_to='backstage/')),
                ('audio_content', models.FileField(blank=True, null=True, upload_to='backstage/')),
                ('backstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='affiche.backstage')),
            ],
        ),
    ]
