# Generated by Django 4.2.13 on 2024-06-28 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiche', '0048_alter_backstage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admins', models.ManyToManyField(related_name='theaters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
